version: '3.3'
services:
  mysql:
    image: mysql:5.6
    container_name: mysql
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=microservice
      - MYSQL_ROOT_HOST=%
    ports:
      - 3306:3306


  discovery:
    stdin_open: true
    tty: true
    build:
      context: discovery
      dockerfile: Dockerfile
    container_name: discovery
    # volumes:
    #   - ./config-server:/tmp
    ports:
      - 8081:8081


  gateway:
    stdin_open: true
    tty: true
    build:
      context: gateway
      dockerfile: Dockerfile
    container_name: gateway
    # volumes:
    #   - .:/tmp
    ports:
      - 8080:8080
    depends_on:
      - discovery

      
  auth:
    stdin_open: true
    tty: true
    build:
      context: auth
      dockerfile: Dockerfile
    container_name: auth
    # volumes:
    #   - .:/tmp
    ports:
      - 8083:8083
    depends_on:
      - mysql
      - discovery

  course:
    stdin_open: true
    tty: true
    build:
      context: course
      dockerfile: Dockerfile
    container_name: course
    # volumes:
    #   - .:/tmp
    ports:
      - 8082:8082
    depends_on:
      - mysql
      - discovery
    