# Especifica a versão do Docker Compose
version: '3.3'

# Nesta seção será especificada a configuração de cada container.
services:
  # Container do banco de dados.
  mysql:
    # Imagem utilizada no container.
    image: mysql:5.6
    # Nome do Container.
    container_name: mysql
    # Aqui são passados os parametros usuário, senha, nome do banco a ser criado e o host.
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=microservice
      - MYSQL_ROOT_HOST=%
      - JWT_PRIVATE_KEY=qxBEEQv7E8aviX1KUcdOiF5ve5COUPAr
    # Porta de acesso ao banco de dados.
    ports:
      - 3306:3306

  # Container do discovery.
  discovery:
    stdin_open: true
    tty: true
    build:
      context: discovery
      # Especificando o arquivo de configurações Dockerfile.
      dockerfile: Dockerfile
    container_name: discovery
    environment:
      - JWT_PRIVATE_KEY=qxBEEQv7E8aviX1KUcdOiF5ve5COUPAr
    ports:
      - 8081:8081

  gateway:
    stdin_open: true
    tty: true
    build:
      context: gateway
      dockerfile: Dockerfile
    container_name: gateway
    environment:
      - JWT_PRIVATE_KEY=qxBEEQv7E8aviX1KUcdOiF5ve5COUPAr
    ports:
      - 8080:8080
    # Indica as dependências para a criação desta imagem.
    depends_on:
      - discovery

  auth:
    stdin_open: true
    tty: true
    build:
      context: auth
      dockerfile: Dockerfile
    container_name: auth
    environment:
      - JWT_PRIVATE_KEY=qxBEEQv7E8aviX1KUcdOiF5ve5COUPAr
    ports:
      - 8083:8083
    depends_on:
      - mysql
      - discovery

  course:
    stdin_open: true
    tty: true
    build:
      context: course
      dockerfile: Dockerfile
    container_name: course
    environment:
      - JWT_PRIVATE_KEY=qxBEEQv7E8aviX1KUcdOiF5ve5COUPAr
    ports:
      - 8082:8082
    depends_on:
      - mysql
      - discovery


  discipline:
    stdin_open: true
    tty: true
    build:
      context: discipline
      dockerfile: Dockerfile
    container_name: discipline
    environment:
      - JWT_PRIVATE_KEY=qxBEEQv7E8aviX1KUcdOiF5ve5COUPAr
    ports:
      - 8084:8084
    depends_on:
      - mysql
      - discovery